### ISSUE TITLE
To-Do for dpmData.py

### ISSUE THREAD

**Issue by sakshi-fermi** [fermi-controls/datalogger-to-ml#11]
- [x] Look for a local device list. If found, use that list. 
- [x] Else, use [https://github.com/fermi-controls/linac-logger-device-cleaner/releases/latest/download/linac_logger_drf_requests.txt](url) as the device list.
- [x] Add an argparse tag to specify the version for the filenames.
- [x] Write a helper script to read GitHub file and write to DEVICE_LIST
