### ISSUE TITLE
Generalize and document the use of the data logger

### ISSUE THREAD

**Issue by beauremus** [fermi-controls/datalogger-to-ml#27]
I imagine the process of using this project would be as follows:

1. pip install data_logger
2. Create a config file
3. python -m data_logger --config "path/to/config"

## TODOs to accomplish this

- [ ] Publish package to chablis
- [ ] Add argparse for config
- [ ] Update README describing installation
